CREATE TABLE [EMPLOYEES] (  
    [EmployeeID] TEXT  NOT NULL PRIMARY KEY,
    [Last_Name] TEXT NOT NULL,
    [First_Name] TEXT NOT NULL
);

INSERT INTO EMPLOYEES VALUES("EN1-26", "O'Brien", "Sean");
INSERT INTO EMPLOYEES VALUES("EN1-33", "Guya", "Amy");
INSERT INTO EMPLOYEES VALUES("EN1-35", "Baranco", "Steven");
INSERT INTO EMPLOYEES VALUES("EN1-36", "Roslyn", "Elizabeth");
INSERT INTO EMPLOYEES VALUES("EN1-38", "Schaaf", "Carol");
INSERT INTO EMPLOYEES VALUES("EN1-40", "Wing", "Alexandra");


CREATE TABLE [PROJECTS] (  
    [ProjectNum] TEXT  NOT NULL,
    [ProjectTitle] TEXT NOT NULL
);

INSERT INTO PROJECTS VALUES("30-452-T3", "STAR manual");
INSERT INTO PROJECTS VALUES("30-457-T3", "ISO procedures");
INSERT INTO PROJECTS VALUES("30-482-TC", "Web site");
INSERT INTO PROJECTS VALUES("31-124-T3", "Employee handbook");
INSERT INTO PROJECTS VALUES("31-238-TC", "STAR prototype");
INSERT INTO PROJECTS VALUES("31-238-TC2", "New catalog");
INSERT INTO PROJECTS VALUES("35-152-TC", "STAR pricing");
INSERT INTO PROJECTS VALUES("36-272-TC", "Order system");


CREATE TABLE [EMPLOYEES_PROJECTS] (  
    [EmployeeID] TEXT  NOT NULL,
    [ProjectNum] TEXT NOT NULL,
    PRIMARY KEY (EmployeeID, ProjectNum)
);

INSERT INTO EMPLOYEES_PROJECTS VALUES("EN1-26", "30-452-T3");
INSERT INTO EMPLOYEES_PROJECTS VALUES("EN1-26", "30-457-T3");
INSERT INTO EMPLOYEES_PROJECTS VALUES("EN1-26", "31-124-T3");
INSERT INTO EMPLOYEES_PROJECTS VALUES("EN1-33", "30-328-TC");
INSERT INTO EMPLOYEES_PROJECTS VALUES("EN1-33", "30-452-T3");
INSERT INTO EMPLOYEES_PROJECTS VALUES("EN1-33", "32-244-T3");
INSERT INTO EMPLOYEES_PROJECTS VALUES("EN1-35", "30-452-T3");
INSERT INTO EMPLOYEES_PROJECTS VALUES("EN1-35", "31-238-TC");
INSERT INTO EMPLOYEES_PROJECTS VALUES("EN1-36", "35-152-TC");
INSERT INTO EMPLOYEES_PROJECTS VALUES("EN1-38", "36-272-TC");
INSERT INTO EMPLOYEES_PROJECTS VALUES("EN1-40", "31-238-TC2");
INSERT INTO EMPLOYEES_PROJECTS VALUES("EN1-40", "31-241-TC");
