CREATE TABLE [MANAGERS] (  
    [ProjectMgr] TEXT NOT NULL PRIMARY KEY,
    [Phone] INTEGER NOT NULL
);

INSERT INTO MANAGERS VALUES("Friedman", "2846");
INSERT INTO MANAGERS VALUES("Garrison", "2756");
INSERT INTO MANAGERS VALUES("Jacanda", "2954");
INSERT INTO MANAGERS VALUES("Jones", "3102");
INSERT INTO MANAGERS VALUES("Vance", "3022");

CREATE TABLE [PROJECTS] (  
    [ProjectNum] TEXT  NOT NULL PRIMARY KEY,
    [ProjectTitle] TEXT NOT NULL,
    [ProjectMgr] TEXT NOT NULL,
    FOREIGN KEY(ProjectMgr) REFERENCES MANAGERS(ProjectMgr)
);



INSERT INTO PROJECTS VALUES("30-452-T3", "STAR manual", "Garrison");
INSERT INTO PROJECTS VALUES("30-457-T3", "ISO procedures", "Jacanda");
INSERT INTO PROJECTS VALUES("30-482-TC", "Web site", "Friedman");
INSERT INTO PROJECTS VALUES("31-124-T3", "Employee handbook", "Jones");
INSERT INTO PROJECTS VALUES("31-238-TC", "STAR prototype", "Garrison");
INSERT INTO PROJECTS VALUES("31-241-TC", "New catalog", "Jones");
INSERT INTO PROJECTS VALUES("35-152-TC", "STAR pricing", "Vance");
INSERT INTO PROJECTS VALUES("36-272-TC", "Order system", "Jacanda");